### ISSUE TITLE
Error while plotting

### ISSUE THREAD

**Issue by PineauPaul** [oysstu/pyxtf#12]
First, thanks for the library wich is very useful. 
But i had a little problem with the XTF i generated and the same probleme happen with your fake XTF file generated in write.py
the error AttributeError: 'XTFUnknownPacket' object has no attribute 'Year' appear when i try to plot it.
Do you know the origin of it ?

Thanks,

**Comment by oysstu** [comment]
The XTFUnknownPacket class is used when the "HeaderType" field contains an unimplemented/unknown XTF packet. This is determined by mapping given by a [dictionary](https://github.com/oysstu/pyxtf/blob/62571ec9024d221a8c7e243f0021aadf5a1f645b/pyxtf/xtf_ctypes.py#L959). The XTFPingHeader [sets its HeaderType](https://github.com/oysstu/pyxtf/blob/62571ec9024d221a8c7e243f0021aadf5a1f645b/pyxtf/xtf_ctypes.py#L654) when instantiated in Python automatically, so Ḯm not sure why the plotting does not work for the example write script.

I don't have time to look at this right now, but I'll leave it open until I do, or the issue is resolved.

**Comment by PineauPaul** [comment]
My xtf file was not generated correctly
