### ISSUE TITLE
Writing over 255 pings causes output xtf file to be unreadable.

### ISSUE THREAD

**Issue by ckhartma621** [oysstu/pyxtf#36]
Hello, 

I am trying to use pyxtf to merge port/starboard files from a Kongsberg HISAS. In trying to do this I discovered that when i try and make a file over 255 pings it becomes unreadable. 

I went and tried your example script 'write_xtf.py' and tried manually changing the num_pings value to see if i could duplicate the behavior. 

When creating files with 255 pings or less, there is no issue and there is no problem using pyxtf to read those files. 

When creating files with 256 pings or more, attempting to read that file results in the following error: 

2024-06-04 18:05:45,926 - ERROR - raise RuntimeError('Number of bytes to read exceeds the number of bytes remaining in packet.') 

Given that its is this 255/256 boundary I thought maybe something like 'ping_count' or similar was 8-bit and couldn't handle a value over 255, however, I have looked through all the code base for pyxtf and so far I can't find a value in any of the file attributes that should be larger than 8-bit and isn't.

Last bit of info is that I can successfully read many other xtf files with pyxtf. It is just the ones written using pyxtf that are over 255 pings that appear to have an issue.

Any help you could provide would be most appreciated. Thanks.

**Comment by oysstu** [comment]
Had a quick look at this now, and this was because of the following line
`d0 = np.arange(0, num_samples_per_ping, dtype=np.uint8)*(i+1)`
I was not aware of this, but when a regular python integer is multiplied by an numpy array and exceeds the maximum bound, the array is automatically promoted to the next type. I.e, when i is greater than 255 above, the array is promoted to np.uint16, which makes the packet larger than it should be.

Can you try now, and see if that helps?

Also, the hisas data you're working with is most likely not 8bit, you'll need to set the SampleFormat enumeration to the corresponding data type. See the latest commit. Ideally, this would be read from the numpy arrays when writing, but I don't have time to implement that right now. I'll add an issue to track that improvement.

**Comment by ckhartma621** [comment]
Øystein,

I am so thankful for your response. Especially so quickly. It would be
really awesome to get this up and running.

I am sorry to be difficult, but what exactly should I try differently? Do I
need to manually alter some of the base code or just make changes in my
program (or your example script)? I tried changing that line to
'dtype=np.uint16' but that didn't do much. I checked the raw files I am
dealing with and their data arrays are all already set to dtype=np.uint16.

The 255/256 boundary was about the amount of pings written to the file
(ping headers/ping data), not how many samples are in each data array. Is
there another place where I might need to change a 8 to a 16?

Thanks again for your response and help as I am sure you are busy.

Respectfully,

Christian Hartmann

**Comment by oysstu** [comment]
Since you have 16bit input data, you need to set the SampleFormat field for all ping channel headers. Right now, this needs to be done manually. The default is 0, which is a legacy value defaulting to 8bit, which is why this worked before.

See the following for the correct value of SampleFormat
https://github.com/oysstu/pyxtf/blob/288df5d7837ce9361a89c77bccbe7c28880f6d9b/pyxtf/xtf_ctypes.py#L40-L59

Edit: in other words, you need to do the reverse of the dictionary. That is, assign 3 to SampleFormat.
