### ISSUE TITLE
I met an error when reading a xtf file

### ISSUE THREAD

**Issue by HhuEdison** [oysstu/pyxtf#7]
When I read a xtf file , it caused a problem (which is shown in the error.txt). The experimental data and error are in the zip file below. How can I solve this ? Thanks a lot.
[DataTest.zip](https://github.com/oysstu/pyxtf/files/3525273/DataTest.zip)

**Comment by oysstu** [comment]
The error occurs because the identifier for the XTF packet is 255, which is not documented in the XTF-specification. I recently made a change that returns unknown XTF-packets in raw binary form rather than throwing an error, but have not pushed it to PyPI yet. Try installing directly from github, that should at least let you continue parsing the other packets.

Let me know how it goes

**Comment by oysstu** [comment]
I released a new version on PyPI containing the bugfix in question

**Comment by HhuEdison** [comment]
Yeah, I downloaded the zip file from github, and copied the pyxtf file to the Lib (directory of python ), but it caused the same problem without warning . I am now trying to conjecture and parse the unknown xtf file given by my customer. Could  you please give me some tips ? Thanks again.

**Comment by HhuEdison** [comment]
Sorry, the error has changed as below.
[error.txt](https://github.com/oysstu/pyxtf/files/3527993/error.txt)

**Comment by oysstu** [comment]
Hi,

Your file appears to not be an XTF file at all, but a word document. Rename the extension to .docx and open it there. I suggest you obtain a real XTF file from your customer and try again.

Øystein
